blocks:
  AMETHYST_BLOCK:
    r: 134
    g: 98
    b: 192
  AMETHYST_CLUSTER:
    r: 91
    g: 71
    b: 116
  ANCIENT_DEBRIS:
    r: 96
    g: 64
    b: 56
  ANVIL:
    r: 69
    g: 69
    b: 69
  AZALEA_LEAVES:
    r: 69
    g: 87
    b: 33
  FLOWERING_AZALEA_LEAVES:
    r: 80
    g: 88
    b: 49
  AZALEA:
    r: 57
    g: 72
    b: 27
  BARREL:
    r: 107
    g: 80
    b: 49
  BASALT:
    r: 74
    g: 73
    b: 78
  BEACON:
    r: 108
    g: 218
    b: 212
  BEEHIVE:
    r: 159
    g: 128
    b: 77
  BEE_NEST:
    r: 196
    g: 151
    b: 77
  BLACKSTONE:
    r: 42
    g: 35
    b: 40
  BLAST_FURNACE:
    r: 107
    g: 106
    b: 106
  BLUE_ICE:
    r: 116
    g: 168
    b: 253
  BONE_BLOCK:
    r: 229
    g: 226
    b: 208
  BOOKSHELF:
    r: 113
    g: 91
    b: 58
  BRICK:
    r: 151
    g: 98
    b: 83
  BUDDING_AMETHYST:
    r: 133
    g: 96
    b: 187
  CALCITE:
    r: 223
    g: 224
    b: 220
  CAULDRON:
    r: 74
    g: 73
    b: 74
  CHEST:
    r: 126
    g: 91
    b: 37
  CHISELED_DEEPSLATE:
    r: 54
    g: 54
    b: 55
  CHISELED_NETHER_BRICKS:
    r: 46
    g: 23
    b: 27
  CHISELED_POLISHED_BLACKSTONE:
    r: 52
    g: 47
    b: 55
  CLAY:
    r: 160
    g: 166
    b: 179
  COAL_BLOCK:
    r: 16
    g: 16
    b: 16
  COAL_ORE:
    r: 104
    g: 104
    b: 103
  COARSE_DIRT:
    r: 118
    g: 84
    b: 58
  COBBLED_DEEPSLATE:
    r: 76
    g: 76
    b: 80
  COBBLESTONE:
    r: 128
    g: 127
    b: 128
  MOSSY_COBBLESTONE:
    r: 109
    g: 118
    b: 94
  COMPOSTER:
    r: 112
    g: 70
    b: 32
  BLACK_CONCRETE:
    r: 8
    g: 10
    b: 15
  BLUE_CONCRETE:
    r: 44
    g: 46
    b: 143
  BROWN_CONCRETE:
    r: 96
    g: 59
    b: 31
  CYAN_CONCRETE:
    r: 21
    g: 119
    b: 136
  GRAY_CONCRETE:
    r: 54
    g: 57
    b: 61
  GREEN_CONCRETE:
    r: 73
    g: 91
    b: 36
  LIGHT_BLUE_CONCRETE:
    r: 35
    g: 137
    b: 198
  LIME_CONCRETE:
    r: 94
    g: 168
    b: 24
  MAGENTA_CONCRETE:
    r: 169
    g: 48
    b: 159
  ORANGE_CONCRETE:
    r: 224
    g: 97
    b: 0
  PINK_CONCRETE:
    r: 213
    g: 101
    b: 142
  BLACK_CONCRETE_POWDER:
    r: 25
    g: 26
    b: 32
  BLUE_CONCRETE_POWDER:
    r: 70
    g: 73
    b: 166
  BROWN_CONCRETE_POWDER:
    r: 125
    g: 84
    b: 53
  CYAN_CONCRETE_POWDER:
    r: 36
    g: 148
    b: 157
  GRAY_CONCRETE_POWDER:
    r: 76
    g: 81
    b: 84
  GREEN_CONCRETE_POWDER:
    r: 97
    g: 119
    b: 44
  LIGHT_BLUE_CONCRETE_POWDER:
    r: 74
    g: 181
    b: 213
  LIME_CONCRETE_POWDER:
    r: 125
    g: 189
    b: 41
  MAGENTA_CONCRETE_POWDER:
    r: 192
    g: 83
    b: 184
  ORANGE_CONCRETE_POWDER:
    r: 227
    g: 132
    b: 31
  PINK_CONCRETE_POWDER:
    r: 229
    g: 153
    b: 181
  PURPLE_CONCRETE_POWDER:
    r: 132
    g: 55
    b: 177
  RED_CONCRETE_POWDER:
    r: 168
    g: 54
    b: 50
  LIGHT_GRAY_CONCRETE_POWDER:
    r: 155
    g: 155
    b: 148
  WHITE_CONCRETE_POWDER:
    r: 225
    g: 227
    b: 227
  YELLOW_CONCRETE_POWDER:
    r: 233
    g: 199
    b: 54
  PURPLE_CONCRETE:
    r: 100
    g: 31
    b: 156
  RED_CONCRETE:
    r: 142
    g: 32
    b: 32
  LIGHT_GRAY_CONCRETE:
    r: 125
    g: 125
    b: 115
  WHITE_CONCRETE:
    r: 207
    g: 213
    b: 214
  YELLOW_CONCRETE:
    r: 240
    g: 175
    b: 21
  COPPER_BLOCK:
    r: 190
    g: 106
    b: 78
  COPPER_ORE:
    r: 124
    g: 125
    b: 119
  TUBE_CORAL_BLOCK:
    r: 48
    g: 87
    b: 206
  DEAD_TUBE_CORAL_BLOCK:
    r: 130
    g: 123
    b: 119
  BRAIN_CORAL_BLOCK:
    r: 207
    g: 90
    b: 159
  DEAD_BRAIN_CORAL_BLOCK:
    r: 123
    g: 117
    b: 113
  BUBBLE_CORAL_BLOCK:
    r: 184
    g: 33
    b: 180
  DEAD_BUBBLE_CORAL_BLOCK:
    r: 132
    g: 123
    b: 119
  FIRE_CORAL_BLOCK:
    r: 162
    g: 35
    b: 48
  DEAD_FIRE_CORAL_BLOCK:
    r: 131
    g: 123
    b: 119
  HORN_CORAL_BLOCK:
    r: 216
    g: 200
    b: 66
  DEAD_HORN_CORAL_BLOCK:
    r: 133
    g: 126
    b: 122
  CRACKED_DEEPSLATE_BRICKS:
    r: 63
    g: 63
    b:g: 64
  CRACKED_DEEPSLATE_TILES:
    r: 52
    g: 52
    b:g: 52
  CRACKED_NETHER_BRICKS:
    r: 40
    g: 20
    b: 23
  CRACKED_POLISHED_BLACKSTONE_BRICKS:
    r: 44
    g: 37
    b:g: 44
  CRAFTING_TABLE:
    r: 135
    g: 108
    b:g: 66
  CRIMSON_STEM:
    r: 92
    g: 25
    b:g: 30
  CRIMSON_NYLIUM:
    r: 107
    g: 27
    b: 26
  CRIMSON_PLANKS:
    r: 100
    g: 48
    b: 70
  CRYING_OBSIDIAN:
    r: 33
    g: 10
    b: 61
  CUT_COPPER:
    r: 189
    g: 105
    b: 79
  DEEPSLATE:
    r: 79
    g: 79
    b: 81
  DEEPSLATE_COAL_ORE:
    r: 73
    g: 73
    b: 74
  DEEPSLATE_COPPER_ORE:
    r: 92
    g: 93
    b: 88
  DEEPSLATE_DIAMOND_ORE:
    r: 82
    g: 107
    b: 107
  DEEPSLATE_EMERALD_ORE:
    r: 77
    g: 105
    b: 87
  DEEPSLATE_GOLD_ORE:
    r: 116
    g: 103
    b: 77
  DEEPSLATE_IRON_ORE:
    r: 107
    g: 100
    b: 94
  DEEPSLATE_LAPIS_ORE:
    r: 79
    g: 90
    b: 116
  DEEPSLATE_REDSTONE_ORE:
    r: 105
    g: 72
    b: 73
  DEEPSLATE_TILES:
    r: 55
    g: 54
    b: 55
  DIAMOND_BLOCK:
    r: 100
    g: 237
    b: 228
  DIAMOND_ORE:
    r: 120
    g: 142
    b: 141
  DIRT:
    r: 133
    g: 95
    b: 66
  PODZOL:
    r: 122
    g: 87
    b: 56
  DRIED_KELP_BLOCK:
    r: 38
    g: 49
    b: 29
  DRIPSTONE_BLOCK:
    r: 134
    g: 108
    b: 92
  EMERALD_BLOCK:
    r: 43
    g: 203
    b: 89
  EMERALD_ORE:
    r: 107
    g: 137
    b: 115
  ENCHANTING_TABLE:
    r: 36
    g: 32
    b: 41
  ENDER_CHEST:
    r: 17
    g: 30
    b: 34
  END_PORTAL_FRAME:
    r: 122
    g: 131
    b: 99
  END_STONE_BRICKS:
    r: 218
    g: 224
    b: 162
  END_STONE:
    r: 219
    g: 223
    b: 158
  EXPOSED_COPPER:
    r: 158
    g: 124
    b: 102
  EXPOSED_CUT_COPPER:
    r: 152
    g: 120
    b: 100
  FROSTED_ICE:
    r: 140
    g: 181
    b: 252
  FURNACE:
    r: 123
    g: 123
    b: 123
  GILDED_BLACKSTONE:
    r: 55
    g: 43
    b: 38
  GLASS:
    r: 136
    g: 144
    b: 145
  BLACK_STAINED_GLASS:
    r: 25
    g: 25
    b: 25
  BLUE_STAINED_GLASS:
    r: 51
    g: 76
    b: 178
  BROWN_STAINED_GLASS:
    r: 102
    g: 76
    b: 51
  CYAN_STAINED_GLASS:
    r: 76
    g: 127
    b: 153
  GRAY_STAINED_GLASS:
    r: 76
    g: 76
    b: 76
  GREEN_STAINED_GLASS:
    r: 102
    g: 127
    b: 51
  LIGHT_BLUE_STAINED_GLASS:
    r: 102
    g: 153
    b: 216
  LIME_STAINED_GLASS:
    r: 127
    g: 204
    b: 25
  MAGENTA_STAINED_GLASS:
    r: 178
    g: 76
    b: 216
  ORANGE_STAINED_GLASS:
    r: 216
    g: 127
    b: 51
  PINK_STAINED_GLASS:
    r: 242
    g: 127
    b: 165
  PURPLE_STAINED_GLASS:
    r: 127
    g: 63
    b: 178
  RED_STAINED_GLASS:
    r: 153
    g: 51
    b: 51
  LIGHT_GRAY_STAINED_GLASS:
    r: 153
    g: 153
    b: 153
  WHITE_STAINED_GLASS:
    r: 255
    g: 255
    b: 255
  YELLOW_STAINED_GLASS:
    r: 229
    g: 229
    b: 51
  BLACK_GLAZED_TERRACOTTA:
    r: 68
    g: 30
    b: 32
  BLUE_GLAZED_TERRACOTTA:
    r: 47
    g: 65
    b: 140
  BROWN_GLAZED_TERRACOTTA:
    r: 120
    g: 106
    b: 85
  CYAN_GLAZED_TERRACOTTA:
    r: 51
    g: 117
    b: 124
  GRAY_GLAZED_TERRACOTTA:
    r: 83
    g: 90
    b: 93
  GREEN_GLAZED_TERRACOTTA:
    r: 115
    g: 140
    b: 64
  LIGHT_BLUE_GLAZED_TERRACOTTA:
    r: 96
    g: 166
    b: 209
  LIME_GLAZED_TERRACOTTA:
    r: 165
    g: 198
    b: 55
  MAGENTA_GLAZED_TERRACOTTA:
    r: 208
    g: 100
    b: 192
  ORANGE_GLAZED_TERRACOTTA:
    r: 154
    g: 145
    b: 89
  PINK_GLAZED_TERRACOTTA:
    r: 235
    g: 155
    b: 182
  PURPLE_GLAZED_TERRACOTTA:
    r: 110
    g: 47
    b: 153
  RED_GLAZED_TERRACOTTA:
    r: 182
    g: 59
    b: 53
  LIGHT_GRAY_GLAZED_TERRACOTTA:
    r: 143
    g: 166
    b: 168
  WHITE_GLAZED_TERRACOTTA:
    r: 186
    g: 212
    b: 206
  YELLOW_GLAZED_TERRACOTTA:
    r: 234
    g: 191
    b: 87
  GLOWSTONE:
    r: 171
    g: 130
    b: 84
  GOLD_BLOCK:
    r: 246
    g: 209
    b: 63
  GOLD_ORE:
    r: 146
    g: 134
    b: 105
  GRAVEL:
    r: 132
    g: 127
    b: 126
  HAY_BLOCK:
    r: 167
    g: 137
    b: 38
  HONEYCOMB_BLOCK:
    r: 229
    g: 148
    b: 30
  HONEY_BLOCK:
    r: 250
    g: 188
    b: 57
  ICE:
    r: 145
    g: 183
    b: 253
  PACKED_ICE:
    r: 141
    g: 180
    b: 250
  IRON_BARS:
    r: 65
    g: 66
    b: 64
  IRON_BLOCK:
    r: 222
    g: 222
    b: 222
  IRON_ORE:
    r: 136
    g: 129
    b: 122
  JUKEBOX:
    r: 91
    g: 60
    b: 41
  LAPIS_BLOCK:
    r: 30
    g: 66
    b: 138
  LAPIS_ORE:
    r: 105
    g: 117
    b: 142
  LODESTONE:
    r: 118
    g: 118
    b: 121
  ACACIA_LOG:
    r: 102
    g: 95
    b: 86
  BIRCH_LOG:
    r: 218
    g: 216
    b: 211
  JUNGLE_LOG:
    r: 85
    g: 67
    b: 25
  OAK_LOG:
    r: 107
    g: 84
    b: 50
  SPRUCE_LOG:
    r: 58
    g: 37
    b: 16
  LOOM:
    r: 143
    g: 98
    b: 71
  MAGMA_BLOCK:
    r: 141
    g: 62
    b: 31
  MANGROVE_LOG:
    r: 83
    g: 66
    b: 41
  MANGROVE_PLANKS:
    r: 117
    g: 53
    b: 48
  MANGROVE_ROOTS:
    r: 43
    g: 34
    b: 22
  MELON:
    r: 114
    g: 145
    b: 30
  SPAWNER:
    r: 24
    g: 32
    b: 43
  MOSS_BLOCK:
    r: 89
    g: 110
    b: 45
  MUD:
    r: 60
    g: 57
    b: 60
  MUDDY_MANGROVE_ROOTS:
    r: 68
    g: 58
    b: 47
  MUD_BRICKS:
    r: 137
    g: 104
    b: 79
  MYCELIUM:
    r: 113
    g: 87
    b: 71
  NETHERITE_BLOCK:
    r: 67
    g: 62
    b: 65
  NETHERRACK:
    r: 97
    g: 38
    b: 38
  NETHER_BRICK:
    r: 44
    g: 21
    b: 26
  NETHER_GOLD_ORE:
    r: 116
    g: 56
    b: 42
  NETHER_WART_BLOCK:
    r: 115
    g: 3
    b: 2
  NOTE_BLOCK:
    r: 91
    g: 60
    b: 41
  OBSERVER:
    r: 71
    g: 69
    b: 69
  OBSIDIAN:
    r: 15
    g: 10
    b: 25
  OCHRE_FROGLIGHT:
    r: 246
    g: 235
    b: 184
  OXIDIZED_COPPER:
    r: 80
    g: 160
    b: 131
  OXIDIZED_CUT_COPPER:
    r: 78
    g: 151
    b: 125
  PACKED_MUD:
    r: 142
    g: 106
    b: 79
  PEARLESCENT_FROGLIGHT:
    r: 236
    g: 227
    b: 230
  PISTON:
    r: 112
    g: 106
    b: 97
  ACACIA_PLANKS:
    r: 167
    g: 90
    b: 50
  BIRCH_PLANKS:
    r: 192
    g: 175
    b: 121
  JUNGLE_PLANKS:
    r: 160
    g: 115
    b: 80
  OAK_PLANKS:
    r: 162
    g: 130
    b: 78
  SPRUCE_PLANKS:
    r: 114
    g: 84
    b: 48
  POLISHED_BASALT:
    - 91
    - 90
    - 93
  POLISHED_BLACKSTONE:
    - 52
    - 47
    - 55
  POLISHED_BLACKSTONE_BRICKS:
    - 48
    - 42
    - 49
  POLISHED_DEEPSLATE:
    - 70
    - 70
    - 71
  POWDER_SNOW:
    - 247
    - 253
    - 253
  PRISMARINE_BRICKS:
    - 97
    - 170
    - 157
  DARK_PRISMARINE:
    - 51
    - 90
    - 75
  PRISMARINE:
    - 99
    - 156
    - 151
  PUMPKIN:
    - 197
    - 116
    - 24
  PURPUR_BLOCK:
    - 168
    - 124
    - 168
  PURPUR_PILLAR:
    - 170
    - 127
    - 169
  CHISELED_QUARTZ_BLOCK:
    - 232
    - 227
    - 218
  QUARTZ_BLOCK:
    - 235
    - 229
    - 222
  QUARTZ_BRICKS:
    - 234
    - 228
    - 221
  QUARTZ:
    - 119
    - 67
    - 64
  RAW_COPPER_BLOCK:
    - 155
    - 106
    - 79
  RAW_GOLD_BLOCK:
    - 221
    - 169
    - 46
  RAW_IRON_BLOCK:
    - 166
    - 136
    - 107
  REDSTONE_BLOCK:
    - 171
    - 24
    - 4
  REDSTONE_LAMP:
    - 98
    - 56
    - 30
  REDSTONE_ORE:
    - 141
    - 108
    - 108
  RED_NETHER_BRICKS:
    - 69
    - 7
    - 9
  RED_SAND:
    - 190
    - 102
    - 33
  RED_SANDSTONE:
    - 186
    - 99
    - 29
  SMOOTH_RED_SANDSTONE:
    - 188
    - 101
    - 31
  RESPAWN_ANCHOR:
    - 39
    - 23
    - 63
  SAND:
    - 219
    - 207
    - 163
  SANDSTONE:
    - 216
    - 203
    - 155
  SMOOTH_SANDSTONE:
    - 217
    - 205
    - 158
  SEA_LANTERN:
    - 178
    - 204
    - 194
  SHROOMLIGHT:
    - 241
    - 149
    - 74
  SLIME_BLOCK:
    - 111
    - 191
    - 91
  SMITHING_TABLE:
    - 56
    - 34
    - 35
  SMOKER:
    - 101
    - 91
    - 77
  SMOOTH_BASALT:
    - 72
    - 72
    - 78
  SNOW:
    - 248
    - 254
    - 254
  SOUL_SAND:
    - 81
    - 62
    - 50
  SOUL_SOIL:
    - 75
    - 57
    - 46
  SPONGE:
    - 196
    - 192
    - 74
  WET_SPONGE:
    - 170
    - 180
    - 70
  STONE:
    - 125
    - 125
    - 125
  STONE_BRICKS:
    - 121
    - 121
    - 121
  CRACKED_STONE_BRICKS:
    - 117
    - 117
    - 117
  MOSSY_STONE_BRICKS:
    - 114
    - 120
    - 103
  STONECUTTER:
    - 125
    - 126
    - 125
  ANDESITE:
    - 136
    - 136
    - 136
  POLISHED_ANDESITE:
    - 129
    - 132
    - 131
  DIORITE:
    r: 188
    g: 188
    b: 188
  POLISHED_DIORITE:
    r: 191
    g: 191
    b: 192
  GRANITE:
    r: 149
    g: 102
    b: 85
  POLISHED_GRANITE:
    r: 151
    g: 104
    b: 86
  STONE_SLAB:
    r: 165
    g: 165
    b: 165
  STRIPPED_ACACIA_LOG:
    r: 175
    g: 93
    b: 60
  STRIPPED_BIRCH_LOG:
    r: 198
    g: 177
    b: 119
  STRIPPED_CRIMSON_STEM:
    r: 137
    g: 57
    b: 90
  STRIPPED_DARK_OAK_LOG:
    r: 73
    g: 57
    b: 36
  STRIPPED_JUNGLE_LOG:
    r: 171
    g: 133
    b: 84
  STRIPPED_MANGROVE_LOG:
    r: 119
    g: 54
    b: 48
  STRIPPED_OAK_LOG:
    r: 179
    g: 145
    b: 87
  STRIPPED_SPRUCE_LOG:
    r: 80
    g: 61
    b: 34
  STRIPPED_WARPED_STEM:
    r: 57
    g: 151
    b: 148
  TARGET:
    r: 228
    g: 173
    b: 165
  TNT:
    r: 179
    g: 86
    b: 82
  TUFF:
    r: 107
    g: 108
    b: 102
  WARPED_NYLIUM:
    r: 72
    g: 62
    b: 60
  WARPED_PLANKS:
    r: 43
    g: 104
    b: 98
  WARPED_STEM:
    r: 58
    g: 58
    b: 77
  WARPED_WART_BLOCK:
    r: 22
    g: 120
    b: 121
  WEATHERED_COPPER:
    r: 107
    g: 151
    b: 107
  WEATHERED_CUT_COPPER:
    r: 109
    g: 143
    b: 105
  BLACK_WOOL:
    r: 20
    g: 21
    b: 25
  BLUE_WOOL:
    r: 53
    g: 57
    b: 157
  BROWN_WOOL:
    r: 114
    g: 71
    b: 40
  CYAN_WOOL:
    r: 21
    g: 137
    b: 145
  GRAY_WOOL:
    r: 62
    g: 68
    b: 71
  GREEN_WOOL:
    r: 84
    g: 109
    b: 27
  LIGHT_BLUE_WOOL:
    r: 58
    g: 175
    b: 217
  LIME_WOOL:
    r: 112
    g: 185
    b: 25
  MAGENTA_WOOL:
    r: 189
    g: 68
    b: 179
  ORANGE_WOOL:
    r: 240
    g: 118
    b: 19
  PINK_WOOL:
    r: 237
    g:g: 141
    b: 172
  PURPLE_WOOL:
    r: 121
    g: 42
    b: 172
  RED_WOOL:
    r: 161
    g: 39
    b: 34
  LIGHT_GRAY_WOOL:
    r: 142
    g: 142
    b: 134
  WHITE_WOOL:
    r: 233
    g: 236
    b: 236
  YELLOW_WOOL:
    r: 248
    g: 198
    b: 39
