name: ImageToBlock
version: 1.0.0
main: dev.caveatemptor.imagetoblock.ImageToBlock
api-version: 1.19

commands:

  # TODO: more descriptive command descriptions

  image:
    description: Hello World!
    usage: /image
    permission: op

  url:
    description: Hello World! (2)
    usage: /url
    permission: op

  sizelimit:
    description: Hello World! (3)
    usage: /sizelimits
    permission: op

  colorTolerance:
    description: Hello World! (4)
    usage: /colorTolerance
    permission: op